linters:
  enable-all: true
  disable:
    # TODO
    - dupl
    - lll
    - exhaustruct
    - paralleltest
    # Challengeable
    - gofumpt
    - gci
    - stylecheck
    - revive
    - wsl
    - gochecknoglobals
    - depguard
    - gomnd
    - varnamelen
    - nlreturn
    # Deprecated 
    - deadcode
    - maligned
    - scopelint
    - nosnakecase
    - interfacer
    - varcheck
    - golint
    - ifshort
    - exhaustivestruct
    - structcheck

